apiVersion: v1
kind: Secret
metadata:
  name: kong-cluster-cert
  namespace: kong
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBYTCB5wIJALKoRPxYyteDMAoGCCqGSM49BAMCMBoxGDAWBgNVBAMMD2tvbmdf
    Y2x1c3RlcmluZzAeFw0yMjA2MjAxODA0NThaFw0yNTA2MTkxODA0NThaMBoxGDAW
    BgNVBAMMD2tvbmdfY2x1c3RlcmluZzB2MBAGByqGSM49AgEGBSuBBAAiA2IABEEn
    ARJ/wrKkMVvUmJpu7KVNiLHIDI7hZWbEODCWlUNhh4cXfOISuhP4C3HHOHvEii8t
    naJf3yW7MQiH/w3e3USEnLJja9TCiBivVEFAN84B5LjgC9e2goDlAcFqNMnKwTAK
    BggqhkjOPQQDAgNpADBmAjEAlA2V7hA2cveEvmNJuWL4oaBglw9s4CD8fzrcNWdj
    ze/UR0BURCAHdRd3hN8Y2GhBAjEAvimVdhafe4BYIZMkjLJ8Z/9UbaWk7EwNMAxN
    Ro+sH6EgVxdSZ57yyawkw0lYx99j
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDD8PpRx7/MxE2mDC+/4
    9poZve6FSoXCapvUHAN+1bAGdYb4H5fJ5TgiBNjDxgwYpkOhZANiAARBJwESf8Ky
    pDFb1JiabuylTYixyAyO4WVmxDgwlpVDYYeHF3ziEroT+Atxxzh7xIovLZ2iX98l
    uzEIh/8N3t1EhJyyY2vUwogYr1RBQDfOAeS44AvXtoKA5QHBajTJysE=
    -----END PRIVATE KEY-----
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-enterprise-license
  namespace: kong
stringData:
  license: |
    {
      "license": {
        <PUT YOU LICENSE HERE>
      }
    }
